# Generated by Django 2.1 on 2019-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(blank=True, help_text='boss昵称', max_length=10, null=True, verbose_name='boss昵称')),
                ('mobile', models.CharField(blank=True, help_text='手机号', max_length=11, null=True, verbose_name='手机号')),
                ('boss_level', models.CharField(blank=True, help_text='level', max_length=11, null=True, verbose_name='level')),
            ],
            options={
                'db_table': 'boss',
            },
        ),
    ]
