# Generated by Django 2.1 on 2019-07-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='PageJson',
        ),
    ]
