# Generated by Django 2.1 on 2019-07-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190725_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagejson',
            options={'verbose_name': '科室', 'verbose_name_plural': '科室'},
        ),
    ]
