# Generated by Django 2.1 on 2019-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180813_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='手机号', max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
